name: Generate Snake Game

on:
  schedule: # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 

      - name: Generate Snake Game from commits
        id: snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy Snake Game to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
